[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pressure"
version = "1.0.0"
description = "Foot pressure and stability estimation"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Keaton Kraiger", email = "keaton.kraiger@gmail.com" }
]

# Read dependencies from requirements.txt
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
where = ["."]
include = ["pressure*"]

[tool.setuptools]
include-package-data = true