data:
  dataset: underpressure
  data_type: UNDERPRESSURE_POS
  pressure_shape:
  - 2
  - 16
  contact_shape:
  - 4
  pose_key: positions
  target_key: forces
  contact_key: contacts
  source_fps: 100
  input_fps: 30
  target_fps: 30
  add_confidence: true
  normalize_pose: true
  normalize_force_by_weight: false
  preload_to_shared_memory: true
  use_skeleton_augmentation: false
  skeletons_basis_std: 2.0
  skeletons_offsets_std: 0.0075
  skeletons_lengths_std: 0.015
  skeletons_asymmetric: false
  pad_edges: true
  test_subjects:
  - S8
  - S9
  - S10
  active_only: false
  chunk_data: false
  chunk_size: 5000
  contact_threshold: 0.1
  num_regions:
  - 2
  - 1
  pressure_is_distribution: false
  sequence_length: 9
  shuffle_data: true
  subject_wise_max_norm: false
  subject_wise_weight_norm: false
  use_regions: false
  view: 1
  binary_contact: true
  gt_com: false

default:
  checkpoint_path: checkpoints
  data_path: UnderPressure/dataset
  loso: false
  device: cuda
  log_interval: 50
  log_path: log
  mode: ['contact', 'pressure']
  om: false
  results_path: Results
  seed: 0
  subjects: all
  test: false
  train: true
  eval: true

eval:
  bad_frames_in_seq_thresh: 0
  checkpoint_flag: best
  eval_results_path: stats
  save_output: true
  zero_conf_thresh: 0
  load_extra_joints: false

loss:
  pressure_loss: mse

  com_reduction: mean
  contact_reduction: mean
  pressure_reduction: mean
  final_reduction:

  lambda_com: 0
  lambda_contact: 1
  lambda_pressure: 1

network:
  contact_conditioned: false
  decoder_dim: 128
  dropout: 0.2
  mlp_dim: 1024
  model: footformer
  norm_first: false
  num_heads: 8
  num_layers: 4
  pool: weighted
  pos: learnable
  pose_embed_dim: 512
  pose_embedder: gcn
  transformer: multi

training:
  batch_size: 64
  dataloader_workers: 4
  decay: 0.01
  early_stop_patience: 6
  epochs: 100
  lr: 0.0002
  max_grad_norm: 0.5
  normalize: null
  optimizer: adamw
  per_sub_epochs: null
  scheduler: cosine_warmup
  smoothing_window: 6
  train_val_split: 0.9
  val_every: 2
  warmup_steps: 1000

viz:
  enabled: false
  fps: 30
  dpi: 300
  save_format: 'png'
  colormap: 'jet'
  plt_style: 'default'
  figures:
    pressure:
      figsize: [10, 8]
      view_angle: [34, -145]
    contact:
      figsize: [2, 6]
      show_colorbar: true
      show_both_feet: true
      mirror: true
    com:
      figsize: [6, 6]
      view_angle_3d: [30, 45]
  collage:
    enabled: false
    samples_per_viz: 8
    stack_vertical: true
  video:
    dpi: 100
    downsample: 1
    enabled: false
    modalities: ['pressure']
    preset: 'medium'
    crf: 23
    video_processors: 1
  validation:
    enabled: false
    samples_per_epoch: 8
